SELECT 
    CONCAT(CASE
		WHEN MUNIC_RES LIKE '53%' THEN '530010'
		ELSE MUNIC_RES
	END, SUBSTR(DT_INTER, 1, 4)) AS chave,
    SUBSTR(DT_INTER, 1, 4) as ano,
    CASE
		WHEN MUNIC_RES LIKE '53%' THEN '530010'
		ELSE MUNIC_RES
	END AS CODMUNRES,
    CASE
        WHEN (DIAG_PRINC LIKE 'E10%' OR DIAG_PRINC LIKE 'E11%' OR DIAG_PRINC LIKE 'E12%' OR DIAG_PRINC LIKE 'E13%' OR DIAG_PRINC LIKE 'E14%') THEN 'Diabetes Mellitus'
		WHEN (DIAG_PRINC LIKE 'I%') THEN 'Doenças do aparelho circulatório'
    END as doenca,
    COUNT(DISTINCT N_AIH) as quantidade
FROM Dados.sih.RD
WHERE
    (DT_INTER IS NOT NULL AND DT_INTER != '')
    AND MUNIC_RES NOT LIKE '%0000'
    AND SUBSTR(DT_INTER, 1, 4) IN ('2015', '2016', '2017', '2018', '2019', '2020', '2021')
    AND ((DIAG_PRINC LIKE 'E10%' OR DIAG_PRINC LIKE 'E11%' OR DIAG_PRINC LIKE 'E12%' OR DIAG_PRINC LIKE 'E13%' OR DIAG_PRINC LIKE 'E14%') OR (DIAG_PRINC LIKE 'I%'))
GROUP BY
    CONCAT(MUNIC_RES, SUBSTR(DT_INTER, 1, 4)),
    SUBSTR(DT_INTER, 1, 4),
    MUNIC_RES,
    CASE
        WHEN (DIAG_PRINC LIKE 'E10%' OR DIAG_PRINC LIKE 'E11%' OR DIAG_PRINC LIKE 'E12%' OR DIAG_PRINC LIKE 'E13%' OR DIAG_PRINC LIKE 'E14%') THEN 'Diabetes Mellitus'
		WHEN (DIAG_PRINC LIKE 'I%') THEN 'Doenças do aparelho circulatório'
    END